#pragma once
#include <exception>
#include <string>
#include <iostream>
#include <SDL.h>
#include <vector>
#include "SDL_image.h"
#include "windows.h"
#include <random>
#include "vld.h"
#include <SDL_mixer.h>